### ISSUE TITLE
`npm run coverage` error.

### ISSUE THREAD

**Issue by HelloYie** [Seedstars/django-react-redux-jwt-base#9]
Hello, when I run `npm run coverage`, I got a error:

```
➜  django-react-redux-jwt-base git:(master) ✗ npm run coverage         

> django-react-redux-jwt-base@1.0.0 coverage /opt/django-react-redux-jwt-base
> istanbul cover node_modules/mocha/bin/_mocha -- --require tests/require --recursive --compilers js:babel-core/register --colors --reporter dot tests/js/

Warning: `valueLink` prop on `input` is deprecated; set `value` and `onChange` instead.


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  58 passing (341ms)

Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/index.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/Root/DevTools.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/Root/Root.dev.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/Root/Root.prod.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/index.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/reducers/index.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/routes.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/store/configureStore.dev.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/store/configureStore.prod.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/utils/requireAuthentication.js
/opt/django-react-redux-jwt-base/node_modules/.npminstall/istanbul-api/1.0.0-aplha.1/istanbul-api/lib/reporter.js:80
        reportSource = libReport.createReportSource(coverageMap, opts);
                                 ^

TypeError: libReport.createReportSource is not a function
    at Object.Reporter.write (/opt/django-react-redux-jwt-base/node_modules/.npminstall/istanbul-api/1.0.0-aplha.1/istanbul-api/lib/reporter.js:80:34)
    at exitFn (/opt/django-react-redux-jwt-base/node_modules/.npminstall/istanbul-api/1.0.0-aplha.1/istanbul-api/lib/run-cover.js:127:18)
    at process.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
    at process.exit (internal/process.js:79:15)
    at done (/opt/django-react-redux-jwt-base/node_modules/.npminstall/mocha/2.4.5/mocha/bin/_mocha:416:32)
    at afterWrite (_stream_writable.js:355:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)


npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/yie/.nvm/versions/node/v5.10.1/bin/node" "/Users/yie/.nvm/versions/node/v5.10.1/bin/npm" "run" "coverage"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! django-react-redux-jwt-base@1.0.0 coverage: `istanbul cover node_modules/mocha/bin/_mocha -- --require tests/require --recursive --compilers js:babel-core/register --colors --reporter dot tests/js/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the django-react-redux-jwt-base@1.0.0 coverage script 'istanbul cover node_modules/mocha/bin/_mocha -- --require tests/require --recursive --compilers js:babel-core/register --colors --reporter dot tests/js/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the django-react-redux-jwt-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     istanbul cover node_modules/mocha/bin/_mocha -- --require tests/require --recursive --compilers js:babel-core/register --colors --reporter dot tests/js/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs django-react-redux-jwt-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls django-react-redux-jwt-base
```

**Comment by almeidarruben** [comment]
Hi,

Thanks for your feedback.
We've already fixed the problem last week. Today it will be committed.

Cheers.

**Comment by HelloYie** [comment]
Thank you!  I hope it comming soon. 👍

**Comment by almeidarruben** [comment]
Committed!
Please test now.

Cheers :)

**Comment by HelloYie** [comment]
Thanks!  But ... `npm run coverage` still have errors ?

```
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/index.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/Root/DevTools.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/Root/Root.dev.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/containers/Root/Root.prod.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/index.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/reducers/index.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/routes.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/store/configureStore.dev.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/store/configureStore.prod.js
Unable to post-instrument: /opt/django-react-redux-jwt-base/src/static/utils/requireAuthentication.js
/opt/django-react-redux-jwt-base/node_modules/.npminstall/istanbul-api/1.0.0-aplha.1/istanbul-api/lib/reporter.js:80
        reportSource = libReport.createReportSource(coverageMap, opts);
                                 ^

TypeError: libReport.createReportSource is not a function
    at Object.Reporter.write (/opt/django-react-redux-jwt-base/node_modules/.npminstall/istanbul-api/1.0.0-aplha.1/istanbul-api/lib/reporter.js:80:34)
    at exitFn (/opt/django-react-redux-jwt-base/node_modules/.npminstall/istanbul-api/1.0.0-aplha.1/istanbul-api/lib/run-cover.js:127:18)
    at process.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
    at process.exit (internal/process.js:79:15)
    at done (/opt/django-react-redux-jwt-base/node_modules/.npminstall/mocha/2.4.5/mocha/bin/_mocha:416:32)
    at afterWrite (_stream_writable.js:355:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by almeidarruben** [comment]
You have something wrong with your system configuration.

You should get an output like the following:
![coverage](https://cloud.githubusercontent.com/assets/5800027/15178740/508c9ee8-176f-11e6-8a10-90eb6f27ee9a.png)

Try running inside your home directory.
Cheers :)

**Comment by HelloYie** [comment]
Done~ Thank you very much!  I find it's my fault. I use `cnpm install`  instead of ` npm install`, because I am in china. I think something wrong with `cnpm install`.
